// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// import { ApolloClient, HttpLink, InMemoryCache } from "@apollo/client";
// import { ApolloProvider } from "@apollo/client/react";

// const client = new ApolloClient({
//   link: new HttpLink({'http://localhost:3000/api/graphql'}),
//   cache: new InMemoryCache(),
// });

// export default function Layout({children}: {children: React.ReactNode}) {
//   return <ApolloProvider client={client}>{children}</ApolloProvider>
// }

// "use client"
// import { ApolloClient, HttpLink, InMemoryCache } from "@apollo/client";
// import { ApolloProvider } from "@apollo/client/react";

// const client = new ApolloClient({
//   link: new HttpLink({
//     uri: 'http://localhost:3000/api/graphql',
//   }),
//   cache: new InMemoryCache(),
// });

// export default function Layout({ children }: { children: React.ReactNode }) {
//   return <ApolloProvider client={client}>{children}</ApolloProvider>;
// }


"use client"
import { ApolloClient, HttpLink, InMemoryCache } from "@apollo/client";
import { ApolloProvider } from "@apollo/client/react";

const client = new ApolloClient({
  link: new HttpLink({
    uri: 'http://localhost:3000/api/graphql',
  }),
  cache: new InMemoryCache(),
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ApolloProvider client={client}>
          {children}
        </ApolloProvider>
      </body>
    </html>
  );
}
